version: 2

sources:
  - name: peoplenet
    database: PROD_DIG
    schema: peoplenet
    tables:
      - name: performxbydriverdata

  - name: cccfilec
    database: PROD_DIG
    schema: cccfilec
    tables:
      - name: unitsrv
      - name: op0516aa
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
      - name: op0568flt
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
          loaded_at_query: "select max(to_timestamp_tz(to_char(convert_timezone('America/Chicago', 'UTC', FIADDD), 'YYYY-MM-DD HH24:MI:SS.FF9') || ' +00:00')) as loaded_at from PROD_DIG.CCCFILEC.OP0568FLT"
      - name: op0131sch
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
          loaded_at_query: "select max(to_timestamp_tz(to_char(convert_timezone('America/Chicago', 'UTC', SCHADDD), 'YYYY-MM-DD HH24:MI:SS.FF9') || ' +00:00')) as loaded_at from PROD_DIG.CCCFILEC.OP0131SCH"
      - name: op0568trp
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
          loaded_at_query: "select max(to_timestamp_tz(to_char(convert_timezone('America/Chicago', 'UTC', TDTMS), 'YYYY-MM-DD HH24:MI:SS.FF9') || ' +00:00')) as loaded_at from PROD_DIG.CCCFILEC.OP0568TRP"
      - name: op0710bp
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
          loaded_at_query: "select max(to_timestamp_tz(to_char(convert_timezone('America/Chicago', 'UTC', PROCESSED_TMS), 'YYYY-MM-DD HH24:MI:SS.FF9') || ' +00:00')) as loaded_at from PROD_DIG.CCCFILEC.OP0710BP"

  - name: cccfilet
    database: PROD_DIG
    schema: cccfilet
    tables:
      - name: unitsrv

  - name: dbo
    database: PROD_DIG
    schema: dbo
    tables:
      - name: dim_date
      - name: dim_time
      - name: late_fees_billing
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
          loaded_at_query: "select max(to_timestamp_tz(to_char(convert_timezone('America/Chicago', 'UTC', EARLY_APPT_DATETIME), 'YYYY-MM-DD HH24:MI:SS.FF9') || ' +00:00')) as loaded_at from PROD_DIG.DBO.LATE_FEES_BILLING"

  - name: iesfilec
    database: PROD_DIG
    schema: iesfilec
    tables:
      - name: units
      - name: billing
      - name: order
        identifier: ORDER
        quoting:
          identifier: true
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
      - name: stopoff
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
      - name: custmast
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
      - name: cities
      - name: comment
        config:
          freshness:
            warn_after: {count: 30, period: minute}
            error_after: {count: 60, period: minute}
